parameters:
    Application.name: gitorade
    
services:
    Application:
        class: Symfony\Component\Console\Application
        arguments: ["%Application.name%"]
    Gitorade:
        class: Sadekbaroudi\Gitorade\Gitorade
    
    #Commands
    MergeUp:
        class: Sadekbaroudi\Gitorade\Command\MergeUp
    
    # Configs
    BranchConfiguration:
        class: Sadekbaroudi\Gitorade\Configuration\Type\BranchConfiguration
    GitConfiguration:
        class: Sadekbaroudi\Gitorade\Configuration\Type\GitConfiguration
    GithubConfiguration:
        class: Sadekbaroudi\Gitorade\Configuration\Type\GithubConfiguration
    
    GithubClient:
        class: Github\Client
    GitWrapper:
        class: GitWrapper\GitWrapper
        arguments: ["%GitWrapper.git_binary%"]
    
    OperationStateManager:
        class: Sadekbaroudi\OperationState\OperationStateManager
    
    BranchManager:
        class: Sadekbaroudi\Gitorade\Branches\BranchManager
